name: Generate files and deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  jekyll:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Generate player and vs files
      run: src/bin/generate

    - name: Generate team files
      run: src/bin/generate-teams

    - name: Set event sponsors
      run: src/bin/set-sponsors

    - name: Standardize event names
      run: src/bin/standardize-event-names

    - uses:  helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
